CREATE TABLE diario_financeiro (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   titulo VARCHAR(255) NOT NULL,

                                   tipo VARCHAR(40) NOT NULL,

                                   data DATE NOT NULL,

                                   conteudo TEXT NOT NULL,

                                   usuario_id BIGINT NOT NULL,

                                   ativo BOOLEAN NOT NULL DEFAULT TRUE,

                                   criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   atualizado_em TIMESTAMP,

                                   CONSTRAINT fk_diario_usuario
                                       FOREIGN KEY (usuario_id)
                                           REFERENCES usuarios(id)
);