CREATE TABLE itens_compra (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              nome VARCHAR(255) NOT NULL,
                              observacao TEXT,
                              data DATE NOT NULL,

                              quantidade INTEGER NOT NULL DEFAULT 1,
                              prioridade VARCHAR(10) NOT NULL,

                              preco_estimado NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
                              preco_pago NUMERIC(12, 2) NOT NULL DEFAULT 0.00,

                              comprado BOOLEAN NOT NULL DEFAULT FALSE,
                              nao_comprar_novamente BOOLEAN NOT NULL DEFAULT FALSE,

                              usuario_id BIGINT NOT NULL,

                              ativo BOOLEAN NOT NULL DEFAULT TRUE,

                              criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              atualizado_em TIMESTAMP,

                              CONSTRAINT fk_item_compra_usuario
                                  FOREIGN KEY (usuario_id)
                                      REFERENCES usuarios(id),

                              CONSTRAINT chk_item_compra_quantidade
                                  CHECK (quantidade >= 1),

                              CONSTRAINT chk_item_compra_preco_estimado
                                  CHECK (preco_estimado >= 0),

                              CONSTRAINT chk_item_compra_preco_pago
                                  CHECK (preco_pago >= 0)
);