spring.application.name=Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/financeai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.main.web-application-type=servlet
spring.ai.openai.api-key=${OPENAI_API_KEY:temp-placeholder}